### Health check
GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks?search=task&completed=0&orderBy=created_at-desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM5MTIyNjI0LCJleHAiOjE3MzkxMjk4MjQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.juUseK7gw8GNPswl6Yr__F2wM_4JAjnQagLkdUHPe4Djxx9ud_gFNFxnoAAvBIc9-pdIYh3IYWf2-wpL3fVSl-FX1zSlmuuCuWLpCwc7N1kGaLtn1d8W4oQ0dpLNErPMJ1K55vtDsfCCh8lgozVyYJ5eUoyjXsFUG8RAUIaMhgzE6p46bR1mpgCHyGj5X-SbXhpW5jssvLMIs9l2-Ye3HwMn3HDkbj5_IDX23S1eIsY0S85BdJVcIQx_ftir1cqmwA3jG2ZnNLDTxkFKJfgRb2t2xSHm1wYV7WN9DayLb5POmU2SNXgjzG9gK3HGs1MfH9YpbbYakmAg65kCW_rIBA

### GET task by ID
GET http://localhost:3000/v1/tasks/cm3d7slq90002z3mcend29988 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3MzkxNTc2LCJleHAiOjE3MzczOTg3NzYsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.GhaIg3EH3eTW8Rw69Xm0eHSodyE4bov4nUI5sCrjCbkrlqjK2vq8Vyh9GZ1AzmyVre_KbjWiIGJet3jsYN10ueXo6B8pHroF4hoq_ja1ik3kbKCkTluDTBwspVPlVPronX5cTYWwQX9HppnwizPOaCxqVqMXhX2XirvC0Cj6RilVIxCHDbifGrK42bk-I5ohoyjY9zrLilsNw_Xh2Vl2wb6h7mycAcyll5aHSld2LHBmu50D7IjDIhrrbJhqd-QcedFno14R-S6DHh-w8XkYfvazx5pH9as3cP5sVSyDddqds6OfU-odKmjuscgQZHWattUjT_VlW-0keV2BKguaYQ
### Create task
POST http://localhost:3000/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3ODM0OTY5LCJleHAiOjE3Mzc4NDIxNjksInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.vRCaktgbWIhZyG1Jund01qmsgQCf-gvG1WkFdd9-XJNIx9HJYHwQNzFc5vJ60dOXHGK3exq7KLqiN7IqV5yKof1PY2zjgVPZ1l-NyNkZkeXWBnU7_llIVVET6U75d1ZkBPHl4B5NYBHUcBeNwnqlIWflqvxnZZgQdhfsgj19n9DyBZMRpH68H9HJuNPKczBsVxKRRIVdrCgvgG1trnfC5_kPbWiGV5l03hyVt3qY--4rVGmI0tky2Nn84zn-5tFtmIr--ZHmB5Q3juUs-kydL9BHrBFvw3FEmp3xSLd_TEYFkIlkHsGdsRHkQAxd1vD4mlgvzoOde3GZfwid-VlO0Q

{
    "name": "Yet another cool task"
}

### Update Task
PUT http://localhost:3000/v1/tasks/cm3d7slq90002z3mcend29988 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3MzkxNTc2LCJleHAiOjE3MzczOTg3NzYsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.GhaIg3EH3eTW8Rw69Xm0eHSodyE4bov4nUI5sCrjCbkrlqjK2vq8Vyh9GZ1AzmyVre_KbjWiIGJet3jsYN10ueXo6B8pHroF4hoq_ja1ik3kbKCkTluDTBwspVPlVPronX5cTYWwQX9HppnwizPOaCxqVqMXhX2XirvC0Cj6RilVIxCHDbifGrK42bk-I5ohoyjY9zrLilsNw_Xh2Vl2wb6h7mycAcyll5aHSld2LHBmu50D7IjDIhrrbJhqd-QcedFno14R-S6DHh-w8XkYfvazx5pH9as3cP5sVSyDddqds6OfU-odKmjuscgQZHWattUjT_VlW-0keV2BKguaYQ

{
    "project_id": "cm3d7slph0000z3mcv9iyp6a7"
}


### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3OTIwMzgwLCJleHAiOjE3Mzc5Mjc1ODAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.insLF-G6V1LZSlNtPbfpnKY_7QUoEYrKkX0PGYfGUuF-siGD4eIZQp4csmY6-8-oW_rVn-87EOOMrwBmxxKwZj5R1LnNPZ7Z645rMmH2IpExz4Y7q4LtbQs9WlLNZU8Kfi-zxwfK_hDHwLCMK0T5dYeHdcqvqi-WQ9mLhpOIKFLEIeOGr4OnnYe7-ZdgHvs6zXYtN5K3jWJStF3a1MSfThyyASMlKOdu_L9MDEx9BJbm8PjqZqObDxqyRKu7q_e-LfGmMA76I06I32Rsv8fODlvdVzVhfqKPL2dijA_d69XCdhUjMDz9pLvOpQ5Ibu6rp3aCtMcjCqhKepPvpZo_Qg

### GET project by ID
GET http://localhost:3000/v1/projects/cm3d7slph0000z3mcv9iyp6a7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM2OTUzODU3LCJleHAiOjE3MzY5NjEwNTcsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.1EjTeRlGexJbc8-9UsV6cJd5QASp_txsAI7pLHXg1kXDbcBkl6RYw5pTU2V8Rt7GUXYcuPlOkL_9Mo0FeHOiiEYFaDVVPYPLICGMzYb14VW4alcEmVD9_f4ua9GkJb887tLo6XmQBp6BSVWz6De3jALkP83LJJ2gjZwtiD2-0fNeN46xTYVUGdxFCHRV3zniVUBAKmKZoHt15aNZh7JSj20QKlBhT4rocJU_3TZw7Fen36cFLm0gtMZBgZj42pNyMi-fQhYehysjZCu_jq0a0s31xCv8vYtEclXfswFP2bkYaSaZt2tIaacb_c39tBM9XYI4iNUMxrou4m_AEm-GQA

### GET project's tasks
GET http://localhost:3000/v1/projects/cm3d7slph0000z3mcv9iyp6a7/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3MzkxNTc2LCJleHAiOjE3MzczOTg3NzYsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.GhaIg3EH3eTW8Rw69Xm0eHSodyE4bov4nUI5sCrjCbkrlqjK2vq8Vyh9GZ1AzmyVre_KbjWiIGJet3jsYN10ueXo6B8pHroF4hoq_ja1ik3kbKCkTluDTBwspVPlVPronX5cTYWwQX9HppnwizPOaCxqVqMXhX2XirvC0Cj6RilVIxCHDbifGrK42bk-I5ohoyjY9zrLilsNw_Xh2Vl2wb6h7mycAcyll5aHSld2LHBmu50D7IjDIhrrbJhqd-QcedFno14R-S6DHh-w8XkYfvazx5pH9as3cP5sVSyDddqds6OfU-odKmjuscgQZHWattUjT_VlW-0keV2BKguaYQ