### Health check
GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM0MjgxNDg0LCJleHAiOjE3MzQyODg2ODQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.bzge5iuDu1H7lwq7yi1n2-kGGV55PQQsCp6gNMFkKobhETrhEPH8r96Cxi39-OPQR0M7Za26KjZP5q2DbdIP9r7cIsKqX4QDDF_TenjNhEFfP__eVMRAkO5Y7gt1EW89NI2HZC52nbDuJ9liChXU59NDWQicjvupGV__hl8dSETDG02ufVfXPz0pRDY9WO-530UhsAM4V5J84QhAt6ocNnn6sCzDBfVN_WCKu1sdO27zLpOxm1ajCFDpVjcq2HPddXEm67sWPUwaEcgOrkk5QKm6YGjGQ6dOEX-nr82aAR3Eod0susYkQf1lZvR5XK7DuhpDpgVbwWq7n_FZajJmPg

### GET task by ID
GET http://localhost:3000/v1/tasks/cm2vxib0w0003356lrlx4wovk HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTZjMTY1My03YjEzLTQ5YmQtOTQ5OS01MzAwN2VhZDAxMjYiLCJpYXQiOjE3MzExODk2NjMsImV4cCI6MTczMTE5MzI2MywiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.X0aV8VvE_vD_OIOG-fo2ROG2jmg4ktZT7zVIogyrcAk

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1


### GET project by ID
GET http://localhost:3000/v1/projects/cm2vxdpyq0000356l75iydjog HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/cm2vxdpyq0000356l75iydjog/tasks HTTP/1.1
